name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build targets
        run: |
          chmod +x sh/build_all.sh
          sh/build_all.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-targets
          path: output/

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: logs/
